"""init

Revision ID: 6bcc8602dab8
Revises: 
Create Date: 2026-02-08 04:24:27.099318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bcc8602dab8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False, comment='Уникальное имя пользователя'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Email пользователя'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Хэшированный пароль'),
    sa.Column('first_name', sa.String(length=100), nullable=True, comment='Имя пользователя'),
    sa.Column('last_name', sa.String(length=100), nullable=True, comment='Фамилия пользователя'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активен ли аккаунт'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Подтвержден ли аккаунт'),
    sa.Column('is_online', sa.Boolean(), nullable=False, comment='Оналайн ли пользователь сейчас'),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False, comment='Последний посещение'),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False, comment='Включены ли уведомления'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата создания аккаунта'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Дата последнего обновления профиля'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True, comment='Название чата (для групповых чатов)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание чата (для групповых)'),
    sa.Column('chat_type', sa.String(length=20), nullable=False, comment='Тип чата: private (личный), group (групповой), channel (канал)'),
    sa.Column('is_private', sa.Boolean(), nullable=False, comment='Приватный ли чат (True) или публичный (False)'),
    sa.Column('private_hash', sa.String(length=64), nullable=True, comment='Хэш для быстрого поиска приватных чатов между двумя пользователями'),
    sa.Column('creator_id', sa.Integer(), nullable=False, comment='ID пользователя, который создал чат'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активен ли чат'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='URL аватара чата'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата создания чата'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Дата последнего обновления (сообщения/настроек)'),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True, comment='Дата последнего сообщения в чате'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_private_hash'), 'chats', ['private_hash'], unique=True)
    op.create_table('chat_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False, comment='ID чата'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID пользователя'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='Роль: owner, admin, member'),
    sa.Column('is_muted', sa.Boolean(), nullable=False, comment='Заглушен ли чат для этого пользователя'),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False, comment='Включены ли уведомления для этого чата'),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False, comment='Когда пользователь присоединился к чату'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=30), nullable=False, comment='Тип сообщения: text, image, file'),
    sa.Column('sender_id', sa.Integer(), nullable=False, comment='ID отправителя'),
    sa.Column('chat_id', sa.Integer(), nullable=False, comment='ID чата'),
    sa.Column('reply_to_id', sa.Integer(), nullable=True, comment='ID сообщения на которое отвечаем'),
    sa.Column('is_edited', sa.Boolean(), nullable=False, comment='Было ли сообщение отредактировано'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Удалено ли сообщение (soft delete)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Когда сообщение было удалено'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата отправки сообщения'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Дата последнего редактирования'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('chat_members')
    op.drop_index(op.f('ix_chats_private_hash'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
